### ISSUE TITLE
Thumbnail UI TODO's

### ISSUE THREAD

**Issue by imalsogreg** [CBMM/petersonfaces#2]
- [x] Don't let selections block wheel-zoom events
- [x] Fix selection alignment issue
- [x] Consider not blurring the background image (too slow?)  <- Slowness was due to redraw
- [x] Window is constantly redrawing at 60Hz. Why?      <- Redraw was due to event loop
- [x] Allow addition of new rectangular selections
- [x] Handle modifying a selection by click & drag on a corner  <- out of scope
- [x] When wheel-zooming, center the zoom on mouse position (rather than (0,0))  <- No big-image zooming
